# Generated by Django 3.2.18 on 2023-04-20 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('choose1_content', models.TextField()),
                ('choose2_content', models.TextField()),
                ('choose1_users', models.ManyToManyField(related_name='choose1_post', to=settings.AUTH_USER_MODEL)),
                ('choose2_users', models.ManyToManyField(related_name='choose2_post', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
