# Generated by Django 3.2.18 on 2023-04-20 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='choose1_content',
            new_name='select1_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='choose2_content',
            new_name='select2_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='choose1_users',
        ),
        migrations.RemoveField(
            model_name='post',
            name='choose2_users',
        ),
        migrations.AddField(
            model_name='post',
            name='select1_users',
            field=models.ManyToManyField(related_name='select1_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='select2_users',
            field=models.ManyToManyField(related_name='select2_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
