# Generated by Django 3.2.18 on 2023-04-21 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_comment_post_emote_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_post',
            name='like_users',
            field=models.ManyToManyField(related_name='like_comment_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='emote_users',
            field=models.ManyToManyField(related_name='emote_posts', through='posts.Emote_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
